### ISSUE TITLE
既存のモデルへの適用

### ISSUE THREAD

**Issue by esperecyan** [sotanmochi/HandPoseTransferForOculusQuest#2]
VRIKを使用しているモデルがあるのですが、こちらで公開されているスクリプトで、ハンドトラッキングから指の動きのみ反映させるという使い方はできますでしょうか？

**Comment by sotanmochi** [comment]
VRIKを使用しているモデルに適用したことはありませんが、OculusHandPoseTransfer.csが指の動きを処理しているスクリプトなので、これを上手く使ってもらえば実現できるのではないでしょうか。
OculusWristController.csは手首の処理をしていますが、こちらはVRIKに合わせて改変が必要かもしれません。

**Comment by esperecyan** [comment]
返答ありがとうございます。
ためしに [HandPoseTransferForOculusQuest-test.zip](https://github.com/sotanmochi/HandPoseTransferForOculusQuest/files/5221688/HandPoseTransferForOculusQuest-test.zip) のようにシーンを作成し、Oculus Linkで再生してみたのですが、OculusHandPoseTransferコンポーネントのTarget Humanoid Avatarに設定したモデルの指が動かず、以下の例外が発生します。
なにか他に設定が必要でしょうか。

環境は次の通りです。
HandPoseTransferForOculusQuest 2020.05.08
Oculus Integration 20.0
Unity 2019.4.10f1
Windows 10 1903

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <fb001e01371b4adca20013e0ac763896>:0)
HandPoseTransfer.OculusQuest.OculusHandPoseTransfer.UpdateHandSkeletonBones (System.Boolean isLeftHand) (at Assets/HandPoseTransfer/Scripts/OculusHandPoseTransfer.cs:191)
HandPoseTransfer.OculusQuest.OculusHandPoseTransfer.LateUpdate () (at Assets/HandPoseTransfer/Scripts/OculusHandPoseTransfer.cs:59)
```

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <fb001e01371b4adca20013e0ac763896>:0)
HandPoseTransfer.OculusQuest.OculusHandPoseTransfer.UpdateHandSkeletonBones (System.Boolean isLeftHand) (at Assets/HandPoseTransfer/Scripts/OculusHandPoseTransfer.cs:191)
HandPoseTransfer.OculusQuest.OculusHandPoseTransfer.LateUpdate () (at Assets/HandPoseTransfer/Scripts/OculusHandPoseTransfer.cs:55)
```

**Comment by esperecyan** [comment]
以下の手順でプロジェクト自体をクローンしてみたのですが、スクリーンショットのように手が固定された状態になり、動作を確認できませんでした。どこか手順が間違っているところなどはあるでしょうか。

1. https://github.com/sotanmochi/HandPoseTransferForOculusQuest をクローン
2. Unity Hubで、Unity バージョン「2018.4.21f1」、ターゲット「Android」にしてプロジェクトを開く
3. 以下のページからOculus Integration 16.0をダウンロードし、インポート
   https://developer.oculus.com/downloads/package/unity-integration-archive/16.0/
4. 「Oculus Utilities has detected that a newer OVRPlugin is avaiable. Using he newest version is recommended. Do you want to enable it? Current version: (Unknown) Available version: 1.48.0」のダイアログに「No」
5. 「New spatializer plugin found. Do you want to upgrade? If you choose 'Upgrade', the old plugin will be renamed  to AudioPluginOculusSpatializer.old」のダイアログに「Don't upgrade」
6. シーン「Assets/HandPoseTransfer/Examples/Scenes/HandPoseTransferForOculusQuest.unity」を開く
7. Oculus Linkで再生

![](https://user-images.githubusercontent.com/3625160/93155411-00686d00-f741-11ea-9197-7d297597c88e.png)

**Comment by sotanmochi** [comment]
原因を調査中なのですがOculus Questのソフトウェアのランタイムバージョンは20.0.0ですか？
Quest本体を20.0にしたら、手のボーンを表示するだけのサンプルシーン（Assets/HandPoseTransfer/Utilities/Scenes/OVRHandBoneVisualizer.unity）すらまともに動かない状態になりました。
バージョンのアップデートで何か仕様が変わった影響だと思いますが、まだ原因が分かっていないので調査継続中です。

**Comment by esperecyan** [comment]
Oculus Questの情報に表示されているバージョンは以下の通りです。

システムバージョン 9041200171800000
バージョン 20.0.0.431.509.242741616
ランタイムバージョン 20.0.0.431.509.242741604
OSバージョン user-904120.17180.0

いちおう、Oculus LinkのPC側のOculusアプリバージョンは 20.0.0.289.509 です。

よろしくお願いします。

**Comment by Rhime-design** [comment]
https://github.com/sotanmochi/HandPoseTransferForOculusQuest/tree/cf6c1f859b2e7a92a48654002e03613b4f9ede35 からダウンロードしたプロジェクトを元にテストさせてもらいましたが、同様に動作が確認できなかったので報告してみます。

▼動作環境
OculusQuest v20.0.0～
Unity 2018.4.20f1
HandPoseTransferForOculusQuest 2020.05.08
Oculus Integration 20.1
Windows10 1909

▼エラーについて
- コンソールには`KeyNotFoundException: The given key was not present in the dictionary.～`と表示されているのを確認しました。

- OculusHandPoseTransfer.csをオンにしているとHMD内の画面がフリーズしてしまい使えませんでした(一瞬動きますが、画面が止まり砂時計がずっと回ってしまいます)。
- OculusHandPoseTransfer.csをオフにすると、ハンドトラッキングで両手のIKを操作することはできましたが指を動かすことができませんでした。
- OculusWristController.csのオンオフは”フリーズ””両手のトラッキング”"指の操作状況"に影響はありませんでした。
- VroidからUnityちゃんへモデル切り替えしても同様でした。

**Comment by sotanmochi** [comment]
修正版をリリースしたのでこちらを試してみてください
https://github.com/sotanmochi/HandPoseTransferForOculusQuest/releases/tag/2020.11.03

Oculus Linkでのハンドトラッキングも有効化しました（Unityエディタでのみ動作テスト済み）

動作確認環境
- Unity 2018.4.28f1
- Oculus Integration 20.1
- Oculus Quest 20.0.0～
- Windows 10 (Version: 1909)

**Comment by utamizu** [comment]
ハンドトラッキングをunitychanでやってみようと思います。
HandPoseTransferをimportしてどこにアタッチすれば良いのでしょうか。
初歩的な質問で申し訳ありませんが、よろしくお願いします。

**Comment by utamizu** [comment]
Unityちゃんに適用すると指は動くのですが、手首から先の位置がずれています。
どのあたりを修正すれば良いのでしょうか

**Comment by esperecyan** [comment]
指が動くのを確認できました！　対応有り難うございます！

**Comment by sotanmochi** [comment]
@utamizu 
サンプルシーンを再確認しましたが、ユニティちゃんの場合も特に問題なく動いています。
不具合のようでしたら、別のIssueを新しく作成して、画像か動画で状況を教えていただけると助かります。
