### ISSUE TITLE
HandPoseTransferの流用方法について

### ISSUE THREAD

**Issue by utamizu** [sotanmochi/HandPoseTransferForOculusQuest#4]
Vitaへの適用方法を参考にUnityちゃんに適用してみました。
buildしたところ指はトラッキングできているようですが位置が合っていないようです。
どのあたりを修正すれば良いのでしょうか。
初歩的な質問で申し訳ありませんが、ご教授ください。
<img width="717" alt="設定画面" src="https://user-images.githubusercontent.com/55833592/98621402-86bcbc00-234a-11eb-9b79-b0d2930c4d63.png">
![オキュラスキャプチャ](https://user-images.githubusercontent.com/55833592/98621418-8ae8d980-234a-11eb-955b-4d05c38cbbf3.jpg)

**Comment by sotanmochi-cvr** [comment]
手首の位置（主に高さ）が合っていない場合は、OculusHandPoseTransferのBodyPositionCorrectionの値を変えてみてください。
ユニティちゃんの場合、-0.18ぐらいが良いかと思います。

![20201117_HandPoseTransfer_Kohaku01](https://user-images.githubusercontent.com/70558028/99398579-f244f180-2927-11eb-81fc-cb870e0fa2df.jpg)

**Comment by sotanmochi-cvr** [comment]
プレイヤーとキャラクターの体格に差がある場合、現実の手の位置とほぼ一致する範囲には限界があります。
そういった場合は、キャラクターモデルのスケールを調整してプレイヤーの体格との差を小さくするなどの工夫が必要です。

下の画像は腕を前にまっすぐ伸ばした状態ですが、ユニティちゃんの方が体が小さいのでプレイヤーの手がある位置には届いてないです。

![20201117_HandPoseTransfer_Kohaku02](https://user-images.githubusercontent.com/70558028/99399507-18b75c80-2929-11eb-9fff-f7946e70c531.jpg)

**Comment by sotanmochi** [comment]
手首の位置（主に高さ）が合っていない場合は、OculusHandPoseTransferのBodyPositionCorrectionの値を変えてみてください。
ユニティちゃんの場合、-0.18ぐらいが良いかと思います。

![20201117_HandPoseTransfer_Kohaku01](https://user-images.githubusercontent.com/16936357/99399976-c165bc00-2929-11eb-9af2-61e09342c9bb.jpg)

**Comment by sotanmochi** [comment]
プレイヤーとキャラクターの体格に差がある場合、現実の手の位置とほぼ一致する範囲には限界があります。
そういった場合は、キャラクターモデルのスケールを調整してプレイヤーの体格との差を小さくするなどの工夫が必要です。

下の画像は腕を前にまっすぐ伸ばした状態ですが、ユニティちゃんの方が体が小さいのでプレイヤーの手がある位置には届いてないです。

![20201117_HandPoseTransfer_Kohaku02](https://user-images.githubusercontent.com/16936357/99400011-ce82ab00-2929-11eb-8418-702cb4176ae8.jpg)

**Comment by utamizu** [comment]
ご回答ありがとうございます。修正できました！
