### ISSUE TITLE
ハンドトラッキング情報の取得について

### ISSUE THREAD

**Issue by utamizu** [sotanmochi/HandPoseTransferForOculusQuest#5]
ハンドトラッキングに使っている指の座標情報を取得したいのですが、どの情報を用いれば取得できますでしょうか。

**Comment by utamizu** [comment]
> ハンドトラッキングに使っている指の座標情報を取得したいのですが、どの情報を用いれば取得できますでしょうか。

**Comment by sotanmochi** [comment]
Utilitiesに置いてあるOVRHandBoneVisualizerの実装を参考にしてください
Assets/HandPoseTransfer/Utilities/Scripts/OVRHandBoneVisualizer.cs
Assets/HandPoseTransfer/Utilities/Scenes/OVRHandBoneVisualizer.unity

**Comment by utamizu** [comment]
ありがとうございます。試してみます。
